resources:
    - name: fortigate-ibm-ha-repo
      type: git
      icon: github
      source:
          uri: https://github.com/fortinet/ibm-fortigate-AP-HA-terraform-deploy.git
          branch: teams_alerts
    - name: terraform-image
      type: registry-image
      icon: terraform
      source:
          repository: hashicorp/terraform
          tag: 1.1.5
    - name: alert
      type: teams-notification
      source:
          url: ((ibm_ci.webhook))

resource_types:
    - name: teams-notification
      type: docker-image
      source:
          repository: navicore/teams-notification-resource
          tag: latest

teams_failure_notification: &teams_failure_notification
    put: alert
    params:
        color: FF0000
        text: |
            Deployment tests failed.
        title: Failure
        actionName: FortiGate AP HA IBM Cloud Terraform Pipeline
        actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

jobs:
    - name: terraform-deployment
      plan:
          - get: terraform-image
          - get: fortigate-ibm-ha-repo
            trigger: true

          - task: terraform-init
            image: terraform-image
            config:
                inputs:
                    - name: fortigate-ibm-ha-repo
                outputs:
                    - name: fortigate-ibm-ha-repo
                platform: linux
                run:
                    path: terraform
                    dir: fortigate-ibm-ha-repo
                    args:
                        - init

          - task: terraform-plan
            image: terraform-image
            config:
                inputs:
                    - name: fortigate-ibm-ha-repo
                outputs:
                    - name: fortigate-ibm-ha-repo
                platform: linux
                run:
                    path: terraform
                    dir: fortigate-ibm-ha-repo
                    args:
                        - plan
                        - -var
                        - SSH_PUBLIC_KEY=((ibm_ci.ssh_public_key))
                        - -var
                        - REGION=((ibm_ci.region))
                        - -var
                        - ZONE=((ibm_ci.zone))
                        - -var
                        - VPC=((ibm_ci.vpc))
                        - -var
                        - SUBNET_1=((ibm_ci.subnet_1))
                        - -var
                        - SUBNET_2=((ibm_ci.subnet_2))
                        - -var
                        - SUBNET_3=((ibm_ci.subnet_3))
                        - -var
                        - SUBNET_4=((ibm_ci.subnet_4))
                        - -var
                        - FGT1_STATIC_IP_PORT1=((ibm_ci.fgt1_static_ip_port1))
                        - -var
                        - FGT1_STATIC_IP_PORT2=((ibm_ci.fgt1_static_ip_port2))
                        - -var
                        - FGT1_STATIC_IP_PORT3=((ibm_ci.fgt1_static_ip_port3))
                        - -var
                        - FGT1_STATIC_IP_PORT4=((ibm_ci.fgt1_static_ip_port4))
                        - -var
                        - FGT1_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - FGT2_STATIC_IP_PORT1=((ibm_ci.fgt2_static_ip_port1))
                        - -var
                        - FGT2_STATIC_IP_PORT2=((ibm_ci.fgt2_static_ip_port2))
                        - -var
                        - FGT2_STATIC_IP_PORT3=((ibm_ci.fgt2_static_ip_port3))
                        - -var
                        - FGT2_STATIC_IP_PORT4=((ibm_ci.fgt2_static_ip_port4))
                        - -var
                        - FGT2_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - SECURITY_GROUP=((ibm_ci.security_group))
                        - -var
                        - CLUSTER_NAME=fgt-ha-ap-concourse-ci
                        - -var
                        - IBMCLOUD_API_KEY=((ibm_ci.ibmcloud_api_key))

          - task: terraform-apply
            on_failure:
                do:
                    - task: destroy-infrastructure
                      file: fortigate-ibm-ha-repo/ci/pipeline/tasks/terraform-destroy.yml
                      ensure: *teams_failure_notification

            image: terraform-image
            config:
                inputs:
                    - name: fortigate-ibm-ha-repo
                outputs:
                    - name: fortigate-ibm-ha-repo
                platform: linux
                run:
                    path: terraform
                    dir: fortigate-ibm-ha-repo
                    args:
                        - apply
                        - -auto-approve
                        - -var
                        - SSH_PUBLIC_KEY=((ibm_ci.ssh_public_key))
                        - -var
                        - REGION=((ibm_ci.region))
                        - -var
                        - ZONE=((ibm_ci.zone))
                        - -var
                        - VPC=((ibm_ci.vpc))
                        - -var
                        - SUBNET_1=((ibm_ci.subnet_1))
                        - -var
                        - SUBNET_2=((ibm_ci.subnet_2))
                        - -var
                        - SUBNET_3=((ibm_ci.subnet_3))
                        - -var
                        - SUBNET_4=((ibm_ci.subnet_4))
                        - -var
                        - FGT1_STATIC_IP_PORT1=((ibm_ci.fgt1_static_ip_port1))
                        - -var
                        - FGT1_STATIC_IP_PORT2=((ibm_ci.fgt1_static_ip_port2))
                        - -var
                        - FGT1_STATIC_IP_PORT3=((ibm_ci.fgt1_static_ip_port3))
                        - -var
                        - FGT1_STATIC_IP_PORT4=((ibm_ci.fgt1_static_ip_port4))
                        - -var
                        - FGT1_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - FGT2_STATIC_IP_PORT1=((ibm_ci.fgt2_static_ip_port1))
                        - -var
                        - FGT2_STATIC_IP_PORT2=((ibm_ci.fgt2_static_ip_port2))
                        - -var
                        - FGT2_STATIC_IP_PORT3=((ibm_ci.fgt2_static_ip_port3))
                        - -var
                        - FGT2_STATIC_IP_PORT4=((ibm_ci.fgt2_static_ip_port4))
                        - -var
                        - FGT2_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - SECURITY_GROUP=((ibm_ci.security_group))
                        - -var
                        - CLUSTER_NAME=fgt-ha-ap-concourse-ci
                        - -var
                        - IBMCLOUD_API_KEY=((ibm_ci.ibmcloud_api_key))

          - task: terraform-destroy
            image: terraform-image
            config:
                inputs:
                    - name: fortigate-ibm-ha-repo
                outputs:
                    - name: fortigate-ibm-ha-repo
                platform: linux
                run:
                    path: terraform
                    dir: fortigate-ibm-ha-repo
                    args:
                        - destroy
                        - -auto-approve
                        - -var
                        - SSH_PUBLIC_KEY=((ibm_ci.ssh_public_key))
                        - -var
                        - REGION=((ibm_ci.region))
                        - -var
                        - ZONE=((ibm_ci.zone))
                        - -var
                        - VPC=((ibm_ci.vpc))
                        - -var
                        - SUBNET_1=((ibm_ci.subnet_1))
                        - -var
                        - SUBNET_2=((ibm_ci.subnet_2))
                        - -var
                        - SUBNET_3=((ibm_ci.subnet_3))
                        - -var
                        - SUBNET_4=((ibm_ci.subnet_4))
                        - -var
                        - FGT1_STATIC_IP_PORT1=((ibm_ci.fgt1_static_ip_port1))
                        - -var
                        - FGT1_STATIC_IP_PORT2=((ibm_ci.fgt1_static_ip_port2))
                        - -var
                        - FGT1_STATIC_IP_PORT3=((ibm_ci.fgt1_static_ip_port3))
                        - -var
                        - FGT1_STATIC_IP_PORT4=((ibm_ci.fgt1_static_ip_port4))
                        - -var
                        - FGT1_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - FGT2_STATIC_IP_PORT1=((ibm_ci.fgt2_static_ip_port1))
                        - -var
                        - FGT2_STATIC_IP_PORT2=((ibm_ci.fgt2_static_ip_port2))
                        - -var
                        - FGT2_STATIC_IP_PORT3=((ibm_ci.fgt2_static_ip_port3))
                        - -var
                        - FGT2_STATIC_IP_PORT4=((ibm_ci.fgt2_static_ip_port4))
                        - -var
                        - FGT2_PORT4_MGMT_GATEWAY=((ibm_ci.fgt_port4_mgmt_gateway))
                        - -var
                        - SECURITY_GROUP=((ibm_ci.security_group))
                        - -var
                        - CLUSTER_NAME=fgt-ha-ap-concourse-ci
                        - -var
                        - IBMCLOUD_API_KEY=((ibm_ci.ibmcloud_api_key))
